version: '2'

services:
    sdfservice:
        mem_limit: 100m
        hostname: sdfservice-app
        domainname: dtveng.net
        container_name: sdfservice-app
        restart: always
        build: .
        volumes:
            - ./tmp/test:/tmp/test
            - ~/.ssh:/~/.ssh
        ports:
            - 8000:8000
            - 2010:2010
        environment:
            - USERVAR=123
        networks:
            - default
networks:
 default:
   driver : bridge
