#!/bin/bash
# Starting python SimpleHTTPServer for endpoint test

cd /home/gd/Desktop/att

case $1 in
	"start" )
                echo "start python SimpleHTTPServer"
		endpoints=(2018 2009 2020 8081)
		#for i in "$endpoints{[*]}"; do
		#	python -m SimpleHTTPServer "$i"
		#done
		nohup python -m SimpleHTTPServer 2018 &
		nohup python -m SimpleHTTPServer 2009 &
		nohup python -m SimpleHTTPServer 2020 &
		nohup python -m SimpleHTTPServer 8081 &
		;;
	"stop" )
		echo "stop python SimpleHTTPServer"
		kill `ps aux | grep "python -m SimpleHTTPServer"` | grep -v grep | awk '{print $2}' > /dev/null 
		;;
	"restart" )
		echo "restart python SimpleHTTPServer"
  	        kill `ps aux | grep "python -m SimpleHTTPServer"` | grep -v grep | awk '{print $2}' > /dev/null 
		nohup python -m SimpleHTTPServer > /tmp/nohup.out &
		;;
	*)
		echo "need start|stop|restart"
		exit 1
esac
